trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    echo "Node: $(node --version)"
    echo "npm:  $(npm --version)"
  displayName: 'Print Node version'

- task: CodeScanCloudPrepare@3
  inputs:
    CodeScanCloud: 'qa-test_azure'
    organization: 'cs-release-26-0-12'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'azure_devops'
    cliProjectName: 'azure_devops'
    cliSources: '.'
    extraProperties: |
      sonar.qualitygate.wait=true
      sonar.token=squ_6f14a39c57489e8f936493259d69340d0d317b80
- task: CodeScanCloudAnalyze@3
  inputs:
    jdkversion: 'JAVA_HOME_17_X64'
- task: CodeScanCloudPublish@3
  inputs:
    pollingTimeoutSec: '300'